[Desktop]
DesktopShortcuts=Home, Trash, Computer, Network
Wallpaper=/usr/share/backgrounds/lxqt-background.jpg
WallpaperMode=zoom
WallpaperRandomize=false

[System]
Archiver=xarchiver
FallbackIconThemeName=oxygen
Terminal=qterminal

[Window]
AlwaysShowTabs=true
