[General]
iconTheme=Papirus-Dark

[mainmenu]
alignment=Left
icon=/usr/share/icons/hicolor/48x48/apps/start-icon.png
ownIcon=true
type=fancymenu

[kbindicator]
alignment=Right
type=kbindicator

[quicklaunch]
alignment=Left
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/qterminal.desktop
apps\3\desktop=/usr/share/applications/org.kde.kcalc.desktop
apps\4\desktop=/usr/share/applications/xtigervncviewer.desktop
apps\5\desktop=/usr/share/applications/org.kde.kgpg.desktop
apps\6\desktop=/usr/share/applications/org.kde.partitionmanager.desktop
apps\7\desktop=/usr/share/applications/firefox-esr.desktop
apps\8\desktop=/usr/share/applications/torbrowser-tor.desktop
apps\9\desktop=/usr/share/applications/signal-desktop.desktop
apps\size=9
type=quicklaunch


[quicklaunch2]
alignment=left
apps\1\desktop=/usr/share/applications/lxqt-leave.desktop
apps\size=1
type=quicklaunch

[panel1]
plugins=mainmenu, showdesktop, desktopswitch, quicklaunch, taskbar, kbindicator, tray, statusnotifier, mount, volume, worldclock, quicklaunch2

[taskbar]
buttonWidth=200
raiseOnCurrentDesktop=true
